### ISSUE TITLE
Library not wokring

### ISSUE THREAD

**Issue by nauyan** [gfjiangly/cvtools#3]
I have installed cvtools library when I import it I get the following error:

```
>>> import cvtools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nauyan/ComputerVision/cvtools/cvtools/__init__.py", line 12, in <module>
    from .cocotools import *
  File "/home/nauyan/ComputerVision/cvtools/cvtools/cocotools/__init__.py", line 1, in <module>
    from .coco import COCO
  File "/home/nauyan/ComputerVision/cvtools/cvtools/cocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/nauyan/ComputerVision/cvtools/cvtools/cocotools/mask.py", line 4
    import ._mask
```
Please advise regarding this issue.

**Comment by gfjiangly** [comment]
Can you provide details and output of the installation command?

**Comment by nauyan** [comment]
I am installing via pip

**Comment by gfjiangly** [comment]
> I am installing via pip

Please uninstall and try to install using this command:  `pip install cvtoolss==0.0.6a1`

**Comment by nauyan** [comment]
Using `pip install cvtoolss==0.0.6a1` solves the issue.
